groups:
  arm:
    operating_mode: position
    profile_type: time
    profile_velocity: 200
    profile_acceleration: 100
    torque_enable: true

  camera:
    operating_mode: position
    profile_type: velocity
    profile_velocity: 131
    profile_acceleration: 15
    torque_enable: true

singles:
  gripper:
    operating_mode: pwm
    torque_enable: true
