port: /dev/ttyDXL

joint_order: [waist, shoulder, elbow, wrist_angle, gripper, pan, tilt]
sleep_positions: [0, -1.1, 1.55, 0.5, 0, 0, 0]

joint_state_publisher:
  update_rate: 100
  publish_states: true
  topic_name: dynamixel/joint_states

groups:
  arm: [waist, shoulder, elbow, wrist_angle]
  camera: [pan, tilt]

grippers:
  gripper:
    horn_radius: 0.014
    arm_length: 0.024
    left_finger: left_finger
    right_finger: right_finger

sisters:
  pan: tilt

motors:
  waist:
    ID: 1
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 131
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  shoulder:
    ID: 2
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 1
    Velocity_Limit: 131
    Min_Position_Limit: 784
    Max_Position_Limit: 3265
    Secondary_ID: 255

  elbow:
    ID: 3
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 1
    Velocity_Limit: 131
    Min_Position_Limit: 671
    Max_Position_Limit: 3094
    Secondary_ID: 255

  wrist_angle:
    ID: 4
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 1
    Velocity_Limit: 131
    Min_Position_Limit: 910
    Max_Position_Limit: 3447
    Secondary_ID: 255

  gripper:
    ID: 5
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 131
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  pan:
    ID: 10
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 131
    Min_Position_Limit: 1024
    Max_Position_Limit: 3072
    Secondary_ID: 255

  tilt:
    ID: 11
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 1
    Velocity_Limit: 131
    Min_Position_Limit: 1024
    Max_Position_Limit: 3072
    Secondary_ID: 255
